
// This file is autogenerated.

const html_output: string = `

<div class="term" id="post">
    <span class="user">junko</span> 2022-12-26 22:11:43
    <a class="links" id="1672063903" href="#1672063903">No. 1672063903 </a><br />
    
file: <a class="url" href="https://media.tenor.com/6_eRz08T10MAAAAS/vtuber-hachi.gif" title="vtuber-hachi.gif">vtuber-hachi.gif</a>
(image/gif)<br /><a href="https://media.tenor.com/6_eRz08T10MAAAAS/vtuber-hachi.gif"><img class="media" src="https://media.tenor.com/6_eRz08T10MAAAAS/vtuber-hachi.gif" /></a>

    this is a test, if this is working, you should be able to see the very
very wholesome reddit 100% picture of hachi doing a very cute gestures with
her hand.
    <br />
</div>


<div class="term" id="post">
    <span class="user">junko</span> 2022-12-26 22:16:12
    <a class="links" id="1672064172" href="#1672064172">No. 1672064172 </a><br />
    
    oh hey it finally works, finally!!!!
this is so cool!!!! <img src='https://cdn.discordapp.com/emojis/1012441809391206440.webp?size=96&quality=lossless'>

    <br />
</div>

`;

var blog_mount: HTMLElement | null = document.getElementById("blog-mount");

blog_mount!.innerHTML += html_output;

